### PR TITLE
Add pxtorem test case and sync code from `@stylexjs/rollup-plugin` 

### PR DESCRIPTION
**Pull request by hemengke1997**
Thank you for making great lib!

Here's what this PR did:

- add pxtorem test case
- use `vite.mergeConfig` instead `deepmerge`
- sync code from `@stylexjs/rollup-plugin`

BTW, I have some questions:
1. https://github.com/nonzzz/vite-plugin-stylex/blob/master/src/index.ts#L161-L168
Why `invalidateModules` in every transform hook?

2. https://github.com/nonzzz/vite-plugin-stylex/blob/0c04c7158a3c3d084d6d55b1546be8a7a430b1a7/src/index.ts#L182C13-L182C119
`processStylexRules` has been called in `load` hook, maybe we can cache the result and use it in `renderChunk`?

Sorry for my bad english. If you're confused, feel free to correct me.

### CODE REVIEW

**Review by nonzzz — CHANGES_REQUESTED** [review]
isProd is not needed.

**Comment by nonzzz** [comment]
About your question. I will list several reasons.

> Why need `invalidateModules` in every transform hook?
- It's work for vite dev hmr.

> Why re called `processStylexRules` in `renderChunk`?
- First i guess you're understand rollup virtual module. The module only load once. then vite's internal css plugin will handle it. but it only contain the fist file.(The first module to be processed then rollup will skip it. As for why,it's because rollup think this module has been processed) So we should re set the latest css. The `vite:css-post` is work after user plugins so we only fool it.

**Comment by hemengke1997** [comment]
> It's work for vite dev hmr.

So, is `invalidataModules` meant for making `virtual-module` hmr not work?

> (The first module to be processed then rollup will skip it. As for why,it's because rollup think this module has been processed

This is the key! I got it, thanks so much

**Comment by nonzzz** [comment]
@hemengke1997 right. the `invalidataModules` means refresh. Then vite's hmr can be work.

**Review by nonzzz — APPROVED** [review]

**Pull request merged**
